var nsubmnhost="http://www.g2b.go.kr:8081";var nquryhost="http://www.g2b.go.kr:8101";var nbidsslhost="https://www.g2b.go.kr:8143";var nbidhost="http://www.g2b.go.kr:8082";var prpslhost="http://rfp.g2b.go.kr:8426";var prpslsslhost="https://rfp.g2b.go.kr:8427";function bidLink_getBidInfoDtlUrl(taskCl,bidno,bidseq,type){var url="";if(taskCl=='1'||taskCl=='9'){url=nsubmnhost+"/ep/invitation/publish/bidInfoDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&releaseYn=Y&taskClCd="+taskCl;}
if(taskCl=='2'){url=nsubmnhost+"/ep/invitation/publish/bidInfoDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&releaseYn=Y&taskClCd=2";}
if(taskCl=='3'){url=nsubmnhost+"/ep/invitation/publish/bidInfoDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&releaseYn=Y&taskClCd=3";}
if(taskCl=='4'){url=nsubmnhost+"/ep/invitation/publish/bidInfoDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&releaseYn=Y&taskClCd=4";}
if(taskCl=='5'||taskCl=='10'){url=nsubmnhost+"/ep/invitation/publish/bidInfoDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&releaseYn=Y&taskClCd=5";}
if(taskCl=='6'||taskCl=='7'){url=nsubmnhost+"/ep/invitation/publish/bidInfoDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&releaseYn=Y&taskClCd="+taskCl;}
if(taskCl=='20'){url=nsubmnhost+"/ep/invitation/publish/bidInfoDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&releaseYn=Y&taskClCd="+taskCl;}
if(url!=""){if(type=="1"){window.location.href=url;}else if(type=="2"){window.open(url+"&popUpYn=Y","bidInfoDtl","status=yes,resizable=yes,scrollbars=yes,toolbar=no,width=870,height=650");}else if(type=="3"){url=nsubmnhost+"/ep/invitation/publish/bidSummaryInfoDtl.do?bidno="+bidno+"&bidseq="+bidseq;window.open(url,"bidInfoDtl","status=yes,resizable=yes,scrollbars=yes,toolbar=no,width=600,height=650");}else if(type=="4"){window.location.href=url+"&talkYn=Y";}else if(type=="5"){parent.window.location.href=url;}else if(type=="6"){parent.window.location.href=url+"&whereAreYouFrom=bidcentermain";}}}
function bidLink_getBidResultDtlUrl(taskCl,bidno,bidseq,bidcate,rebidno,type){var url="";if(taskCl=='1'||taskCl=='9'){url=nquryhost+"/ep/result/prodBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&bidcate="+bidcate+"&rebidno="+rebidno;}
if(taskCl=='3'){url=nquryhost+"/ep/result/facilBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&rebidno="+rebidno;}
if(taskCl=='5'){url=nquryhost+"/ep/result/serviceBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&rebidno="+rebidno;}
if(taskCl=='6'||taskCl=='7'){url=nquryhost+"/ep/result/leaseBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&bidcate="+bidcate+"&rebidno="+rebidno;}
if(taskCl=='2'){url=nquryhost+"/ep/result/selectFrnBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&bidcate="+bidcate+"&rebidno="+rebidno;}
if(taskCl=='4'){url=nquryhost+"/ep/result/stplBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&bidcate="+bidcate+"&rebidno="+rebidno;}
if(taskCl=='20'){url=nquryhost+"/ep/result/privateBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&bidcate="+bidcate+"&rebidno="+rebidno;}
if(url!=""){if(type=="1"){window.location.href=url;}else if(type=="2"){window.open(url+"&abstractIsPopup=Y","bidResultDtl","status=yes,resizable=yes,scrollbars=yes,toolbar=no,width=860,height=650");}else if(type=="3"){return url;}else if(type=="4"){window.location.href=url+"&whereAreYouFrom=bidProg";}else if(type=="5"){window.location.href=url+"&whereAreYouFrom=piser";}}}
function bidLink_biddingProd(bidno,bidseq){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var popup=window.open(nsubmnhost+"/ep/join/bidding/listItemBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingProdAlert(bidno,bidseq){var message="2015년8월10일부터 공고되는 수요기관 자체 집행 물품 입찰은"+"\r\n안전 입찰서비스를 이용하여야만 입찰서 제출이 가능합니다."+"\r\n(단계별 적용시기는 나라장터 운영자 공지사항 1709번"+"\r\n<나라장터 안전입찰 서비스 본격 시행 안내> 참고)"+"\r\n"+"\r\n조달기업 이용자께서는 반드시 나라장터 「안전 입찰서비스」설치 및"+"\r\n이용방법, 정상 작동 여부 등을 점검하시기 바랍니다."+"\r\n"+"\r\n확인 버튼 클릭시 계속 진행합니다.";alert(message);var x=(screen.width-840)/2;var y=(screen.height-600)/2;var popup=window.open(nsubmnhost+"/ep/join/bidding/listItemBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingProdCate(bidno,bidcate){var x=(screen.width-420)/2;var y=(screen.height-400)/2;var popup=window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docver=2&dummy="+new Date().getTime(),"","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingFacil(bidno){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var bidcate="0";var popup=window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingFacilAlert(arg_bidno,arg_bidseq){var message="2015년7월1일부터 공고되는 수요기관 자체 집행 시설공사 입찰은"+"\r\n안전 입찰서비스를 이용하여야만 입찰서 제출이 가능합니다."+"\r\n(단계별 적용시기는 나라장터 운영자 공지사항 1709번"+"\r\n<나라장터 안전입찰 서비스 본격 시행 안내> 참고)"+"\r\n"+"\r\n조달기업 이용자께서는 반드시 나라장터 「안전 입찰서비스」설치 및"+"\r\n이용방법, 정상 작동 여부 등을 점검하시기 바랍니다."+"\r\n"+"\r\n확인 버튼 클릭시 계속 진행합니다.";alert(message);var x=(screen.width-840)/2;var y=(screen.height-600)/2;var bidcate="0";var popup=window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+arg_bidno+"&bidcate="+bidcate+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingGeneralService(bidno,bidseq){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var popup=window.open(nsubmnhost+"/ep/join/bidding/listItemBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingGeneralServiceAlert(bidno,bidseq){var message="2015년4월6일부터 공고되는 조달청 용역 입찰은"+"\r\n안전 입찰서비스를 이용하여야만 입찰서 제출이 가능합니다."+"\r\n(단계별 적용시기는 나라장터 운영자 공지사항 1622번"+"\r\n<나라장터 안전입찰 서비스 본격 시행 안내> 참고)"+"\r\n"+"\r\n조달기업 이용자께서는 반드시 나라장터 「안전 입찰서비스」설치 및"+"\r\n이용방법, 정상 작동 여부 등을 점검하시기 바랍니다."+"\r\n"+"\r\n확인 버튼 클릭시 계속 진행합니다.";alert(message);var x=(screen.width-840)/2;var y=(screen.height-600)/2;var popup=window.open(nsubmnhost+"/ep/join/bidding/listItemBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingService(bidno){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var bidcate="0";var popup=window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, scrollbars=yes, toolbar=no, status=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingServiceAlert(bidno,bidseq){var message="2015년7월20일부터 공고되는 수요기관 자체 집행 용역 입찰은"+"\r\n안전 입찰서비스를 이용하여야만 입찰서 제출이 가능합니다."+"\r\n(단계별 적용시기는 나라장터 운영자 공지사항 1709번"+"\r\n<나라장터 안전입찰 서비스 본격 시행 안내> 참고)"+"\r\n"+"\r\n조달기업 이용자께서는 반드시 나라장터 「안전 입찰서비스」설치 및"+"\r\n이용방법, 정상 작동 여부 등을 점검하시기 바랍니다."+"\r\n"+"\r\n확인 버튼 클릭시 계속 진행합니다.";alert(message);var x=(screen.width-840)/2;var y=(screen.height-600)/2;var bidcate="0";var popup=window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, scrollbars=yes, toolbar=no, status=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingLease(bidno){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var bidcate="1";var popup=window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingForeign(bidno,bidseq){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var popup=window.open(nsubmnhost+"/ep/join/bidding/listFrnBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingStpl(bidno,bidseq){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var popup=window.open(nsubmnhost+"/ep/join/bidding/listStplBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=yes, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_biddingPrivate(bidno){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var bidcate="0";var popup=window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docver=2&dummy="+new Date().getTime(),"tuchal","left=50, top=50, width=840, height=600, scrollbars=yes, toolbar=no, status=yes, menubar=no, resizable=yes");try{popup.focus();}catch(e){}}
function bidLink_rebiddingProd(bidno,bidseq){window.location=nquryhost+"/ep/result/prodBidResultCateList.do?bidno="+bidno+"&bidseq="+bidseq+"&dummy="+new Date().getTime();}
function bidLink_rebiddingFacil(bidno,bidseq,rebidno){var rebid_no2=0;if(rebidno==''){rebid_no2=0;}else{rebid_no2=eval(rebidno)-1;}
var x=(screen.width-840)/2;var y=(screen.height-600)/2;window.location=nquryhost+"/ep/result/facilBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&rebidno="+rebid_no2+"&progressInfo=재입찰"+"&dummy="+new Date().getTime();}
function bidLink_rebiddingRstService(bidno){var x=(screen.width-840)/2;var y=(screen.height-600)/2;window.location=nquryhost+"/ep/result/listPageIntegrationBidResult.do?bidno="+bidno+"&dummy="+new Date().getTime();}
function bidLink_rebiddingService(bidno,bidseq,rebidno){var rebid_no2=0;if(rebidno==''){rebid_no2=0;}else{rebid_no2=eval(rebidno)-1;}
var x=(screen.width-840)/2;var y=(screen.height-600)/2;window.location=nquryhost+"/ep/result/serviceBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&rebidno="+rebid_no2+"&progressInfo=재입찰"+"&dummy="+new Date().getTime();}
function bidLink_rebiddingLease(bidno,bidseq){var x=(screen.width-840)/2;var y=(screen.height-600)/2;window.location=nquryhost+"/ep/result/leaseBidResultCateList.do?bidno="+bidno+"&bidseq="+bidseq+"&dummy="+new Date().getTime();}
function bidLink_rebiddingPrivate(bidno,bidseq,rebidno){var rebid_no2=0;if(rebidno==''){rebid_no2=0;}else{rebid_no2=eval(rebidno)-1;}
var x=(screen.width-840)/2;var y=(screen.height-600)/2;window.location=nquryhost+"/ep/result/privateBidResultDtl.do?bidno="+bidno+"&bidseq="+bidseq+"&rebidno="+rebid_no2+"&progressInfo=재입찰"+"&dummy="+new Date().getTime();}
function bidLink_jointSppAgtProd(bidno,bidseq){var x=(screen.width-420)/2;var y=(screen.height-400)/2;window.open(nsubmnhost+"/ep/join/bidding/listItemBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&docType=jointSppAgt","tuchal","left=50, top=50, width=840, height=650, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");}
function bidLink_jointSppAgtProdCate(bidno,bidcate){var x=(screen.width-420)/2;var y=(screen.height-400)/2;window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docType=jointSppAgt","","left=50, top=50, width=840, height=600, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");}
function bidLink_jointSppAgtFacil(bidno){var x=(screen.width-420)/2;var y=(screen.height-400)/2;var bidcate="0";window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docType=jointSppAgt","goAppGongDongSu","left=50, top=50, width=840, height=650, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");}
function bidLink_jointSppAgtGeneralService(bidno,bidseq){var x=(screen.width-420)/2;var y=(screen.height-400)/2;window.open(nsubmnhost+"/ep/join/bidding/listItemBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&docType=jointSppAgt","goAppActionTuchal","left=50, top=50, width=840, height=650, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");}
function bidLink_jointSppAgtService(bidno){var x=(screen.width-840)/2;var y=(screen.height-600)/2;var bidcate="0";window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docType=jointSppAgt","goAppGongDongSu","left=50, top=50, width=840, height=650, toolbar=no, status=yes, scrollbars=yes, menubar=no, resizable=yes");}
function bidLink_payFee(bidno,bidcate){var x=(screen.width-420)/2;var y=(screen.height-400)/2;var bugiType="charge";window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&bugiType="+bugiType,"PayFee","left=50, top=50, width=550, height=400, toolbar=no, status=yes, menubar=no, resizable=yes");}
function bidLink_payWarr(taskClCd,bidno,bidseq){var x=(screen.width-420)/2;var y=(screen.height-400)/2;var bugiType="deposit";if(taskClCd=="1"){window.open(nsubmnhost+"/ep/join/bidding/listItemBidcate.do?bidno="+bidno+"&bidseq="+bidseq+"&bugiType="+bugiType,"PayWarr","left=50, top=50, width=800, height=400, toolbar=no, status=yes, menubar=no, resizable=yes");}else{window.open(nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidseq="+bidseq+"&bugiType="+bugiType,"PayWarr","left=50, top=50, width=550, height=400, toolbar=no, status=yes, menubar=no, resizable=yes");}}
function toTalkBid(bidno,bidcate,taskClCd,negoYn){var docType="";if(taskClCd=="1"||taskClCd=="9"){docType="OrderBid";}else if(taskClCd=="2"){docType="BIDFRG";}else if(taskClCd=="3"){docType="ConstructionBid";}else if(taskClCd=="5"){docType="ConstructionBid";}
var virtualClientMadeYn=sendRequestServer("/ep/co/virtualClientMadeCheck.do");if(virtualClientMadeYn==true||virtualClientMadeYn=="true"){alert("전자시담 서비스는 안전입찰에서 지원하지 않는 서비스 입니다.\n\n\r\r 기존 웹방식으로 처리하시기 바랍니다.");return;}
var url=nsubmnhost+"/ep/join/bidding/checkBiddingMandatory.do?bidno="+bidno+"&bidcate="+bidcate+"&docType="+docType+"&negoYn="+negoYn+"&dummy="+new Date().getTime();window.open(url,'chatting','status=yes,resizable=no,scrollbars=yes,toolbar=no,left=10,top=0,width=860,height=800');}
function sendRequestServer(strUrl){var returnDate="";$.ajax({async:false,cache:false,type:"POST",url:strUrl,dataType:"text",success:function(data){returnDate=data;},error:function(){}});return returnDate;}
function pollCallback(){if(xmlHttp.readyState==4){if(xmlHttp.status==200){responseResult=xmlHttp.responseText;}else{var message=xmlHttp.getResponseHeader("Status");if((message==null)||(message.length<=0)){alert("Error! Request status is "+xmlHttp.status);}else{alert(message);}}}}
function ePpropoIntegrateLink(bidno,bidseq,bidcate){if(bidcate==null||bidcate==""){bidcate="0";}
var rfpUrl=prpslhost+"/pss/prsb/PSSPrsbSbmsnRgt.do?"+"exCall=Y"+"&bidNtceNo="+bidno+"&bidNtceOrd="+bidseq+"&bidClsfcNo="+bidcate;popup_openWindowScroll(rfpUrl,"1200","800","ePpropoIntegrate");}
function ePpropodocLink(bidno,bidseq,bidcate,uiGubun){ePpropoIntegrateLink(bidno,bidseq,bidcate);}
function ePpropoResConFirm(bidno,bidseq,bidcate){ePpropoIntegrateLink(bidno,bidseq,bidcate);}
function gotoPropoDocMng(bidno){var url=prpslhost+"/pes/gpe/ebp/openPESEvlBizList.do?exCall=Y&searchBidNtceNo="+bidno;popup_openWindowScroll(url,"1200","800","statusWin");}
function gotoProposalDetail(arg1,arg2,arg3){var nextUrl=prpslhost+"/pes/te/selectPagePESQultatvEvlBgn.do?bidNtceNo="+arg1+"&bidNtceOrd="+arg2+"&bidClsfcNo="+arg3;location.href=nextUrl;return;}
function toPropoDocEvalResultDtl(bidno,bidseq,bidcate,epropoEvalYn){var url="";if(epropoEvalYn=='Y'){url=prpslhost+"/pes/gpe/eam/listPagePESTechEvlRsltLinkP.do"+"?exCall=Y"+"&bidNtceNo="+bidno+"&bidNtceOrd="+bidseq+"&bidClsfcNo="+bidcate;}else{url=nbidhost+"/ep/execution/eproposal/propoDocOffLineEvalResultDtl.do"+"?bidno="+bidno+"&bidseq="+bidseq+"&bidcate="+bidcate;}
popup_openWindowScroll(url,850,650,"propoDocEvalResultDtl");}
function eeOrderAttachFileDownload(isMobileYn,eeOrderAttachFileNo,eeOrderAttachFileSeq){var currProtocolPrpslHost=(location.protocol=="https:"?prpslsslhost:prpslhost);var url=currProtocolPrpslHost+"/cmm/FileDownload.do?atchFileId="+eeOrderAttachFileNo+"&fileSn="+eeOrderAttachFileSeq
if(document.frmEeOrderFileDownload){var f=document.frmEeOrderFileDownload;f.target="_self";f.action=url;f.submit();}else{if(isMobileYn=="Y"){location.href=url;}else{popup_openWindowMsg(url,"500","300","openWin");}}
return;}
function toCrimeHisInfoReqList(formObj,wbidderSelCriteriaCd){var f=formObj;if(wbidderSelCriteriaCd!='1'){alert("국가계약법 공고 일때만 조회 가능합니다.");return;}
f.target='_self'
f.method="post";f.action="/ep/support/report/fwdCrimeHisInfoReqList.do";f.submit();return;}
function toCrimeHisInfoReq(formObj,isOpenDtOverLimitMonth){if(!isOpenDtOverLimitMonth||isOpenDtOverLimitMonth=='false'){alert("실제 개찰 이후 3개월이 지난 공고는 조세포탈여부 조회 불가능합니다.");return;}
var f=formObj;f.target='_self'
f.method="post";f.action="/ep/support/report/fwdCrimeHisInfoReq.do";f.submit();return;}
function toChfInjusticeForInstList(popupYn,bidno,bidseq,bidcate,rebidno,repSupplierCd,bidJoinViewpointCode,whereAreYouFrom){var url="/ep/co/chfInjusticeForInstList.do?"+"bidno="+bidno+"&bidseq="+bidseq+"&bidcate="+bidcate+"&repSupplierCd="+repSupplierCd+"&whereAreYouFrom="+whereAreYouFrom+"&popupYn="+popupYn;if(whereAreYouFrom!="RPT"&&whereAreYouFrom!="WBD"){url+="&rebidno="+rebidno;url+="&bidJoinViewpointCode="+bidJoinViewpointCode;}
if(popupYn=="Y"){popup_openWindowScroll(url,850,600,"chfInjusticeForInstList");}else{location.href=url;}
return;}
function toChfInjusticeDtl(injusticeNo,injusticeModseq){var url="http://www.g2b.go.kr:8070/um/injustice/injusticeBizerHistDtl.do?"+"injusticeNo="+injusticeNo+"&injusticeModseq="+injusticeModseq+"&whereAreYouFrom=BID";popup_openWindowScroll(url,800,650,"chfInjusticeDtl");return;}
function toEvalLinkOk(){return true;}
function toDsgnDocDownload(dsgnDocUnityAttachNo,bidno,bidseq,rebidno,bidcate){var url="http://masstran.g2b.go.kr:8081/masstran/selectMassTranFileDtlPopup.do?unityAtchFileNo="+dsgnDocUnityAttachNo;var insertCnt=0;$.ajax({async:false,cache:false,type:"POST",url:"/ep/invitation/publish/insertDsgnDocAgree.do?bidno="+bidno+"&bidseq="+bidseq+"&reBidno="+rebidno+"&bidcateStr=0",dataType:"text",success:function(data){if(data=="Y"){insertCnt=1;}},error:function(){}});if(insertCnt==1){popup_openWindowScroll(url,830,490,'dsgnDoc');}}